[package]
name = "bend-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bend-lang = { version = "0.2.36" }
tree-sitter-bend = { git = "https://github.com/HigherOrderCO/tree-sitter-bend.git" }
tower-lsp = { version = "0.20", features = ["proposed"] }
tokio = { version = "1.17", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tree-sitter = "0.22"
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"

[build-dependencies]
cc = "1.1"
