[package]
name = "bend-language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-lsp = { version = "0.20", features = ["proposed"]}
tokio = { version = "1.17", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
